GOOD_QUESTS = [
    "See how many push-ups you can do in 5 minutes — pace yourself, take breaks, and record the total.",
    "Walk backward for 2 minutes in a safe open space (bonus if you get curious looks).",
    "Try a wall handstand (or partial handstand with feet on a chair) for as long as you can hold.",
    "Write a short note to your future self 1 year from today — seal it in an envelope or save it digitally.",
    "For one meal today, eat without screens, books, or distractions — just taste every bite.",
    "Take a walk and deliberately photograph 5 things shaped like triangles.",
    "Learn how to introduce yourself in sign language — practice saying “Hi, my name is \_\_\_.”",
    "Watch a 10-minute video on how to tie a knot you’ve never used before, then practice it.",
    "Open a random Wikipedia article and explain what you read in a voice memo as if you’re teaching a class.",
    "Look up one philosophical concept you’ve never heard of and summarize it in one sentence.",
    "Draw a self-portrait with your non-dominant hand — no erasing.",
    "Take a household object (spoon, chair, etc.) and write a haiku from its perspective.",
    "Build a tiny sculpture out of whatever’s on your desk — paperclips, coins, scraps.",
    "Send a photo of something beautiful you saw today to someone you care about.",
    "Ask a friend what their favorite childhood snack was and tell them yours.",
    "Write a 3-sentence review of the last thing someone recommended to you, and send it back to them.",
    "Call or text a relative and ask them one story from their life you’ve never heard before.",
    "Pick one drawer and reorganize it as if you were curating a museum exhibit.",
    "Do a “reset” of one surface (desk, coffee table, kitchen counter) so it looks like no one has ever used it.",
    "Find 3 digital files you don’t need anymore and delete them permanently.",
    "Take a 10-minute “speed tidy” — pick one room and see how much you can improve it in that time.",
    "Count how many times you can clap your hands in 10 seconds — try twice and record your best",
    "Go on a walk and see for how many steps you can walk in a straight line, keep trying to beat your best.",
    "Perfect — you’re looking for “quest families” that lean into playful cognition: short, engaging, but still substantive. Here’s how I’d structure it:",
    "Writing Prompt: Write about the first time you remember feeling proud of yourself.",
    "Writing Prompt: Imagine you wake up tomorrow with a new superpower — what is the first thing you do?",
    "Writing Prompt: Describe your morning routine as if you were a famous celebrity.",
    "Writing Prompt: Write a letter from your pet (or an imaginary one) to you.",
    "Writing Prompt: Invent a local legend about your neighborhood — what story do people tell?",
    "Writing Prompt: Rewrite a memory from your life as if it were a scene in a novel.",
    "Writing Prompt: Pick an object nearby and tell its “origin story.”",
    "Writing Prompt: Write about the smell that most reminds you of home.",
    "Writing Prompt: Imagine someone discovers your journal 100 years from now — what entry do they find?",
    "Writing Prompt: Write a dialogue between your present self and your 10-year-old self.",
    "Estimate how many steps it would take to walk from your home to the nearest grocery store.",
    "Estimate the number of streetlights in your city.",
    "Estimate how many emails you’ve sent in the past year.",
    "Estimate the number of words in your favorite book.",
    "Estimate how many cups of coffee/tea are consumed daily in your country.",
    "Estimate how many people are currently in the nearest stadium/arena (if an event were happening).",
    "Estimate the number of windows in your home/apartment building.",
    "Estimate how many cars pass by your street in an hour.",
    "Estimate the total number of steps you take on an average day.",
    "Estimate how many gallons of water you use in a 10-minute shower.",
    "List every teacher you can remember from school — how many?",
    "Recall the last five meals you ate — how detailed can you be?",
    "Write down as many addresses you’ve ever lived at as you can remember.",
    "Try to name every country you’ve visited (or want to visit) without looking it up.",
    "List every single password you’ve ever used (don’t record them digitally — just memory test).",
    "Recall the first five concerts, movies, or plays you went to — what year and with whom?",
    "Name every pet you’ve ever had (or pets of friends/family you remember).",
    "Write down every phone number you can remember from memory.",
    "Recall all the jobs you’ve had and estimate how many hours you worked at each.",
    "List 10 random small objects you remember from your childhood home.",
    "Find a local landmark or mural you’ve never actually stopped to look at — photograph it and note one detail.",
    "Identify a plant or tree near you using an app or quick search — record its name.",
    "Look up the origin of your street name (or nearest one) and write a one-sentence history.",
    "Read the Wikipedia entry for today’s date and find the oddest historical event.",
    "Sketch a quick floor plan of your living space from memory — then check how accurate it is.",
    "Look up one traditional proverb from another culture and write what you think it means.",
    "Identify the oldest object in your home and write down its story (how you got it, where it came from).",
    "Read a short poem out loud twice — once slowly, once dramatically.",
    "Ask a friend or relative for one “life tip” they swear by",
    "Write down every brand or logo you can see around you in 2 minutes",
    "Estimate how many piano tuners there are in your city",
    "Estimate how many people are awake in your city right now.",
    "Estimate how many pizzas are being delivered in your country in the next hour.",
    "Estimate how many steps it would take to walk the length of your street.",
    "Estimate how many lightbulbs are turned on in your apartment building at this exact moment.",
    "Estimate how many gallons of paint it would take to cover your entire living space.",
    "Estimate how many dogs live within a 1-mile radius of your home.",
    "Estimate how many airplanes are over your country right now.",
    "Estimate how many gallons of water flow through your shower in 1 minute.",
    "Estimate how many words you’ve spoken in your life so far.",
    "Estimate how many chairs exist in your city.",
    "Estimate how many photographs are taken worldwide in a single day.",
    "Estimate how many cups of coffee are consumed on Earth every second.",
    "Estimate how many times your heart has beaten in your lifetime.",
    "Estimate how many songs are being played on Spotify right now.",
    "Estimate how many tennis balls would fit inside your living room.",
    "Estimate how many cars are currently parked vs. moving in your city.",
    "Estimate how many books are in all the libraries of your country combined.",
    "Estimate how many minutes of commercials you’ve watched in your lifetime.",
    "Estimate how many people share your exact birthday worldwide.",
    "Come up with three different explanations for why a traffic light might stay red longer than usual.",
    "Imagine aliens land and see humans jogging — list two possible (but wrong) reasons they’d think we do it.",
    "Write two different “solutions” to the riddle: Why might someone carry an umbrella on a sunny day?",
    "Think of three everyday objects that could double as a musical instrument — describe how.",
    "Create a false but plausible “origin story” for a common phrase you use.",
    "Write a sentence where every word starts with the same letter.",
    "Write a 5-line story where each line must be exactly 7 words.",
    "List 10 things in your home that are blue (or the same color).",
    "Write down as many words as you can that rhyme with “light” in 60 seconds.",
    "Imagine you’re a detective: what three “clues” would you collect from your own room to figure out who you are?",
    "Describe a completely ordinary activity (like brushing teeth) as if it were a dangerous adventure.",
    "Invent a new sport using two existing sports combined.",
    "Pick a random object in your home and research it's material composition and/or its invention.",
    "Look up the population of a country you know almost nothing about and compare it to your own city.",
    "Try to write your signature with both hands at the same time — compare the results.",
    "Count how many unique sounds you can hear in 2 minutes with your eyes closed.",
    "Read the opening sentence of three different books you own — which one is strongest?",
    "Test your reaction time with the ruler-drop method; record your best of five",
    "Identify your dominant eye using the Miles test and note which it is",
    "Measure your favorite mug’s capacity with a measuring cup or scale; write the exact volume",
    "Blind-taste two similar things you own (tap vs filtered water, two teas, or two salts) and write which you prefer and why",
    "Measure your resting heart rate after 5 minutes seated, then 1 minute after 30 squats; record the change",
    "Balance a broom or long stick vertically on your palm; record your longest hold of three tries",
    "Memorize a friend's phone number and test yourself an hour later",
    "Identify the dominant cloud type overhead right now and name it (cirrus, cumulus, stratus, etc.)",
    "Learn how to make an origami frog.",
    "Time yourself reciting the alphabet backwards — repeat once and see if you improve.",
    "Calculate your typing speed using a website",
    "Learn a basic one-handed coin roll or pen spin trick and practice until you pull it off once.",
    "Whistle or hum a note and then check with a tuner app to see how close you are to a true pitch.",
    "Sketch a bicycle from memory — then look at a photo and note what you missed.",
    "Fold a paper airplane and measure how far it flies across a room — adjust and test again.",
]
