"""Add quest template voting

Revision ID: 04f587e8b714
Revises: ba49c86d694d
Create Date: 2025-09-02 15:41:32.128661

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "04f587e8b714"
down_revision = "ba49c86d694d"
branch_labels = None
depends_on = None

# Use existing enum
questrating = postgresql.ENUM(
    "THUMBS_UP",
    "THUMBS_DOWN",
    name="questrating",
    create_type=False,
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sidequest_quest_template_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("quest_template_id", sa.Integer(), nullable=False),
        sa.Column("vote", questrating, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quest_template_id"],
            ["sidequest.sidequest_quest_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sidequest",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sidequest_quest_template_votes", schema="sidequest")
    # ### end Alembic commands ###
