"""poppytracker

Revision ID: 46ecb5a3d012
Revises: 52058c954673
Create Date: 2025-04-24 16:10:25.420785

"""

from datetime import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46ecb5a3d012"
down_revision = "52058c954673"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS poppytracker")
    op.create_table(
        "daily_target",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "date", sa.Date(), nullable=False, server_default=sa.text("CURRENT_DATE")
        ),
        sa.Column("target", sa.Float(), nullable=False, server_default="3.0"),
        sa.Column("last_updated_by", sa.String(length=36), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
        schema="poppytracker",
    )
    op.create_table(
        "feeding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("last_updated_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="poppytracker",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feeding", schema="poppytracker")
    op.drop_table("daily_target", schema="poppytracker")
    op.execute("DROP SCHEMA IF EXISTS poppytracker")
    # ### end Alembic commands ###
