"""Add PoppyTracker tables

Revision ID: 500d08a7e453
Revises: 52058c954673
Create Date: 2025-04-18 21:51:26.902676

"""

from datetime import datetime

import pytz
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "500d08a7e453"
down_revision = "52058c954673"
branch_labels = None
depends_on = None

pacific = pytz.timezone("America/Los_Angeles")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS poppytracker")

    op.create_table(
        "daily_feeding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("daily_target", sa.Float(), nullable=False, server_default="3.0"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("(now() AT TIME ZONE 'America/Los_Angeles')"),
        ),
        sa.Column("last_updated_by", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
        schema="poppytracker",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_feeding", schema="poppytracker")
    op.execute("DROP SCHEMA IF EXISTS poppytracker")
    # ### end Alembic commands ###
