"""stripe

Revision ID: 52058c954673
Revises: 3bea1fa09251
Create Date: 2025-04-13 17:43:03.811588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52058c954673'
down_revision = '3bea1fa09251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
