"""additional_notes

Revision ID: 6076820e36cc
Revises: c20f27143e66
Create Date: 2025-08-31 19:47:09.059178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6076820e36cc'
down_revision = 'c20f27143e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sidequest_users', schema='sidequest') as batch_op:
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sidequest_users', schema='sidequest') as batch_op:
        batch_op.drop_column('additional_notes')

    # ### end Alembic commands ###
