"""quest_board

Revision ID: c20f27143e66
Revises: ecdac675dd29
Create Date: 2025-08-31 14:10:33.615642

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c20f27143e66"
down_revision = "ecdac675dd29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sidequest_quest_boards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("last_refreshed", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="sidequest",
    )
    # create the status enum
    op.execute(
        "CREATE TYPE queststatus AS ENUM ('POTENTIAL', 'ACCEPTED', 'COMPLETED', 'FAILED', 'ABANDONED', 'DECLINED')"
    )
    with op.batch_alter_table("sidequest_quests", schema="sidequest") as batch_op:
        batch_op.add_column(sa.Column("quest_board_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "POTENTIAL",
                    "ACCEPTED",
                    "COMPLETED",
                    "FAILED",
                    "ABANDONED",
                    "DECLINED",
                    name="queststatus",
                ),
                nullable=False,
                server_default="POTENTIAL",
            )
        )
        batch_op.create_foreign_key(
            None,
            "sidequest_quest_boards",
            ["quest_board_id"],
            ["id"],
            referent_schema="sidequest",
        )
        batch_op.drop_column("skipped")
        batch_op.drop_column("selected")
        batch_op.drop_column("completed")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sidequest_quests", schema="sidequest") as batch_op:
        batch_op.add_column(
            sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("selected", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("skipped", sa.BOOLEAN(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("status")
        batch_op.drop_column("quest_board_id")
    op.execute("DROP TYPE queststatus")

    op.drop_table("sidequest_quest_boards", schema="sidequest")
    # ### end Alembic commands ###
