"""adjust poppytracker

Revision ID: cb80341b05bd
Revises: 500d08a7e453
Create Date: 2025-04-24 14:38:48.302451

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cb80341b05bd"
down_revision = "500d08a7e453"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_target",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("last_updated_by", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
        schema="poppytracker",
    )
    op.create_table(
        "feeding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("last_updated_by", sa.String(length=36), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
        schema="poppytracker",
    )
    op.drop_table("daily_feeding", schema="poppytracker")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_feeding",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('poppytracker.daily_feeding_id_seq'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "total_amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "daily_target",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'3'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("(now() AT TIME ZONE 'America/Los_Angeles'::text)"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_updated_by", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="daily_feeding_pkey"),
        sa.UniqueConstraint("date", name="daily_feeding_date_key"),
        schema="poppytracker",
    )
    op.drop_table("feeding", schema="poppytracker")
    op.drop_table("daily_target", schema="poppytracker")
    # ### end Alembic commands ###
