"""anonymous login

Revision ID: ecdac675dd29
Revises: 0fd8b7d1acc0
Create Date: 2025-08-31 11:55:35.100781

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ecdac675dd29"
down_revision = "0fd8b7d1acc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("anon_id", sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint("uq_user_google_id", ["google_id"])
        batch_op.create_unique_constraint("uq_user_apple_id", ["apple_id"])
        batch_op.create_unique_constraint("uq_user_anon_id", ["anon_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_google_id", type_="unique")
        batch_op.drop_constraint("uq_user_apple_id", type_="unique")
        batch_op.drop_constraint("uq_user_anon_id", type_="unique")
        batch_op.drop_column("anon_id")

    # ### end Alembic commands ###
