import "./Privacy.css";

import React from "react";
import { useAuth } from "@/contexts/AuthContext";

const Privacy: React.FC = () => {
  const { user } = useAuth();
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      {user && <p className="mb-4">Hello {user.name}!</p>}
      <p className="text-gray-600 mb-4">Last updated: April 16, 2025</p>

      <div className="space-y-6">
        <section>
          <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
          <p className="mb-4">
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use Our
            Services and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className="mb-4">
            We use Your Personal data to provide and improve Our Services. By
            using Our Services, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Interpretation and Definitions
          </h2>
          <h3 className="text-xl font-semibold mb-2">Interpretation</h3>
          <p className="mb-4">
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 className="text-xl font-semibold mb-2">Definitions</h3>
          <ul className="list-disc pl-6 space-y-2 mb-4">
            <li>
              <strong>Services</strong> refers to all digital products provided
              by the Company, including but not limited to the Website and iOS
              Applications.
            </li>
            <li>
              <strong>Website</strong> refers to www.landonkleinbrodt.com
            </li>
            <li>
              <strong>iOS Applications</strong> refers to any mobile
              applications developed and published by the Company on the Apple
              App Store.
            </li>
            <li>
              <strong>Company</strong> (referred to as either "the Company",
              "We", "Us" or "Our" in this Agreement) refers to Landon
              Kleinbrodt.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the
              Services such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal
              person who processes the data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Services or from
              the Services infrastructure itself.
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the
              Services.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Collecting and Using Your Personal Data
          </h2>
          <h3 className="text-xl font-semibold mb-2">
            Types of Data Collected
          </h3>

          <h4 className="text-lg font-semibold mb-2">Personal Data</h4>
          <p className="mb-4">
            While using Our Services, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul className="list-disc pl-6 space-y-2 mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Usage Data</li>
            <li>Device information (for iOS Applications)</li>
            <li>App-specific data (for iOS Applications)</li>
          </ul>

          <h4 className="text-lg font-semibold mb-2">Usage Data</h4>
          <p className="mb-4">
            Usage Data is collected automatically when using Our Services. Usage
            Data may include information such as:
          </p>
          <ul className="list-disc pl-6 space-y-2 mb-4">
            <li>Your Device's Internet Protocol address (e.g. IP address)</li>
            <li>Browser type and version (for Website)</li>
            <li>Device type and operating system (for iOS Applications)</li>
            <li>The pages of our Services that You visit</li>
            <li>The time and date of Your visit</li>
            <li>The time spent on those pages</li>
            <li>Unique device identifiers</li>
            <li>Other diagnostic data</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Use of Your Personal Data
          </h2>
          <p className="mb-4">
            The Company may use Personal Data for the following purposes:
          </p>
          <ul className="list-disc pl-6 space-y-2 mb-4">
            <li>To provide and maintain our Services</li>
            <li>To manage Your requests</li>
            <li>To contact You</li>
            <li>
              To provide You with news, special offers and general information
            </li>
            <li>To improve our Services</li>
            <li>To monitor the usage of our Services</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To provide customer support</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Security of Your Personal Data
          </h2>
          <p className="mb-4">
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to use
            commercially acceptable means to protect Your Personal Data, We
            cannot guarantee its absolute security.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Links to Other Websites
          </h2>
          <p className="mb-4">
            Our Services may contain links to other websites that are not
            operated by Us. If You click on a third party link, You will be
            directed to that third party's site. We strongly advise You to
            review the Privacy Policy of every site You visit.
          </p>
          <p className="mb-4">
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Changes to this Privacy Policy
          </h2>
          <p className="mb-4">
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </p>
          <p className="mb-4">
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
          <p className="mb-4">
            If you have any questions about this Privacy Policy, You can contact
            us:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>By email: landon@coyote-ai.com</li>
            <li>
              By visiting this page on our website: www.landonkleinbrodt.com
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
};

export default Privacy;
