"""add foreign key

Revision ID: a7fe9939873e
Revises: 72ce8692bc84
Create Date: 2024-05-05 14:36:44.032681

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7fe9939873e"
down_revision = "72ce8692bc84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("songs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("artist_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("song_artist_key", "artists", ["artist_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("songs", schema=None) as batch_op:
        batch_op.drop_constraint("song_artist_key", type_="foreignkey")
        batch_op.drop_column("artist_id")

    # ### end Alembic commands ###
