name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Backend setup and test
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Deploy both frontend and backend
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e  # Exit on any error
            
            # Pull latest code
            cd /var/www/coyote-ai
            git pull origin main
            
            # Backend deployment
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Frontend deployment - builds static files that Nginx serves
            cd frontend
            npm ci
            npm run build || { echo "Frontend build failed"; exit 1; }
            
            # Restart only the application server to pick up backend changes
            # No need to restart Nginx as it automatically serves the new static files
            systemctl restart coyote-ai 